version: '3.8'
services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env.pg
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/pgsql/data/
  api:
    container_name: test-blog
    image: ${TEST_BLOG_IMAGE_NAME}
    depends_on:
      - database
    env_file:
      - .env.prod
    ports:
      - '3000:3000'
  frontend:
    container_name: test-blog-front
    image: ${TEST_FRONT_IMAGE_NAME}
    depends_on:
      - api
    ports:
      - 3002:3002
      
volumes:
  db:
    external: true
